print ("Que dia es hoy?")
fecha = input()
print ("Cuantas calorias ingeriste en la mañana?")
calorias1 = int(input())
print ("Cuantas caloriasingeriste en la comida?")
calorias2 = int(input())
print ("Cuantas calorias ingeriste en la cena?")
calorias3 = int(input())
sum = (calorias1 + calorias2 + calorias3)
print ("Calorias consumidas el 3 de agosto del 2021: " + str(sum))
